const API_BASE_URL = `${process.env.EXPO_PUBLIC_API_URL}/api/stripe`;

export interface PaymentMethod {
  id: string;
  type: string;
  card?: {
    brand: string;
    last4: string;
    exp_month: number;
    exp_year: number;
  };
  isDefault?: boolean;
  isUserAdded?: boolean;
  isAutoGenerated?: boolean;
}

export interface CreatePaymentMethodRequest {
  customerId: string;
  cardNumber?: string;
  expMonth?: number;
  expYear?: number;
  cvc?: string;
  isUserAdded?: boolean;
}

export interface CreatePaymentMethodResponse {
  success: boolean;
  paymentMethod?: PaymentMethod;
  error?: string;
  message?: string;
}

export interface PaymentMethodsResponse {
  success: boolean;
  paymentMethods?: PaymentMethod[];
  hasRealPaymentMethods?: boolean;
  error?: string;
  message?: string;
}

export class PaymentMethodService {
  // 🔒 SECURITY: Sanitize sensitive data from logs
  private static sanitizeLogData(data: any): any {
    if (typeof data === 'object' && data !== null) {
      const sanitized = { ...data };
      
      // Remove sensitive fields from logs
      const sensitiveFields = [
        'cardNumber', 'cvc', 'cvv', 'number', 'client_secret', 'secret'
      ];
      
      Object.keys(sanitized).forEach(key => {
        if (sensitiveFields.some(field => key.toLowerCase().includes(field))) {
          sanitized[key] = '****REDACTED****';
        } else if (typeof sanitized[key] === 'object') {
          sanitized[key] = this.sanitizeLogData(sanitized[key]);
        }
      });
      
      return sanitized;
    }
    return data;
  }

  // Get or create Stripe customer ID for current user
  static async getUserStripeCustomerId(userId: string, email?: string, name?: string): Promise<{ success: boolean; customerId?: string; error?: string }> {
    try {
      console.log('🔄 Getting Stripe customer ID for user:', userId ? 'USER_ID_PROVIDED' : 'NO_USER_ID');
      
      const requestBody: any = { userId };
      if (email) requestBody.email = email;
      if (name) requestBody.name = name;
      
      // 🔒 SECURITY: Log sanitized request data only
      console.log('📤 Request data:', this.sanitizeLogData(requestBody));
      
      const response = await fetch(`${API_BASE_URL}/get-customer-id`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });

      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.error || `HTTP ${response.status}`);
      }

      console.log('✅ Stripe customer ID retrieved successfully');
      return result;
    } catch (error: any) {
      console.error('❌ Error getting Stripe customer ID:', error.message);
      return {
        success: false,
        error: error.message,
      };
    }
  }

  // Get payment methods for current user (automatically handles customer ID)
  static async getPaymentMethodsForUser(userId: string, email?: string, name?: string): Promise<PaymentMethodsResponse> {
    try {
      // First get the user's Stripe customer ID
      const customerResult = await this.getUserStripeCustomerId(userId, email, name);
      
      if (!customerResult.success || !customerResult.customerId) {
        return {
          success: false,
          error: customerResult.error || 'Failed to get customer ID',
          message: 'Failed to get customer ID'
        };
      }

      // Then get their payment methods
      return await this.getPaymentMethods(customerResult.customerId);
    } catch (error: any) {
      console.error('❌ Error getting payment methods for user:', error);
      return {
        success: false,
        error: error.message,
        message: 'Failed to get payment methods for user'
      };
    }
  }

  // Create a new payment method
  static async createPaymentMethod(data: CreatePaymentMethodRequest): Promise<CreatePaymentMethodResponse> {
    try {
      // 🔒 SECURITY: Never log sensitive payment data
      console.log('🔄 Creating payment method for customer:', data.customerId ? 'CUSTOMER_ID_PROVIDED' : 'NO_CUSTOMER_ID');
      
      const response = await fetch(`${API_BASE_URL}/create-payment-method`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.error || `HTTP ${response.status}`);
      }

      console.log('✅ Payment method created successfully');
      return result;
    } catch (error: any) {
      console.error('❌ Error creating payment method:', error.message);
      return {
        success: false,
        error: error.message,
        message: 'Failed to create payment method'
      };
    }
  }

  // Set default payment method
  static async setDefaultPaymentMethod(customerId: string, paymentMethodId: string): Promise<{ success: boolean; error?: string; message?: string }> {
    try {
      console.log('🔄 Setting default payment method:', { customerId, paymentMethodId });
      
      const response = await fetch(`${API_BASE_URL}/set-default-payment-method`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ customerId, paymentMethodId }),
      });

      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.error || `HTTP ${response.status}`);
      }

      console.log('✅ Default payment method set:', result);
      return result;
    } catch (error: any) {
      console.error('❌ Error setting default payment method:', error);
      return {
        success: false,
        error: error.message,
        message: 'Failed to set default payment method'
      };
    }
  }

  // Get customer payment methods
  static async getPaymentMethods(customerId: string): Promise<PaymentMethodsResponse> {
    try {
      console.log('🔄 Getting payment methods for customer:', customerId ? 'CUSTOMER_ID_PROVIDED' : 'NO_CUSTOMER_ID');
      
      const response = await fetch(`${API_BASE_URL}/customer/${customerId}/payment-methods`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.error || `HTTP ${response.status}`);
      }

      // 🔒 SECURITY: Log only safe information about payment methods
      console.log('✅ Payment methods retrieved, count:', result.paymentMethods?.length || 0);
      return result;
    } catch (error: any) {
      console.error('❌ Error getting payment methods:', error.message);
      return {
        success: false,
        error: error.message,
        message: 'Failed to get payment methods'
      };
    }
  }

  // Delete payment method
  static async deletePaymentMethod(paymentMethodId: string): Promise<{ success: boolean; error?: string; message?: string }> {
    try {
      console.log('🔄 Deleting payment method:', paymentMethodId);
      
      const response = await fetch(`${API_BASE_URL}/payment-method/${paymentMethodId}`, {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.error || `HTTP ${response.status}`);
      }

      console.log('✅ Payment method deleted:', result);
      return result;
    } catch (error: any) {
      console.error('❌ Error deleting payment method:', error);
      return {
        success: false,
        error: error.message,
        message: 'Failed to delete payment method'
      };
    }
  }
}
