export interface PaymentMethodResult {
  message?: string;
  success: boolean;
  hasRealPaymentMethods?: boolean;
  paymentMethods?: any[];
  error?: string;
}

export interface PaymentMethod {
  id: string;
  type: string;
  card?: {
    brand: string;
    last4: string;
    exp_month: number;
    exp_year: number;
    funding?: string;
    country?: string;
  };
  created: number;
  isAutoGenerated?: boolean;
  isUserAdded?: boolean;
  isDefault?: boolean;
}

export class PaymentMethodService {
  private static baseUrl = process.env.EXPO_PUBLIC_API_URL;

  static async getPaymentMethodsForUser(
    userId: string,
    userEmail?: string
  ): Promise<PaymentMethodResult> {
    try {
      if (!this.baseUrl) {
        throw new Error('EXPO_PUBLIC_API_URL environment variable is not set');
      }

      const apiUrl = `${this.baseUrl}/api/stripe/user/${userId}/payment-methods`;
      console.log('🔄 PaymentMethodService - Making request to:', apiUrl);
      console.log('🔄 PaymentMethodService - Base URL:', this.baseUrl);
      
      const response = await fetch(apiUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          email: userEmail,
        }),
      });

      console.log('📊 PaymentMethodService - Response status:', response.status);
      console.log('📊 PaymentMethodService - Response ok:', response.ok);

      if (!response.ok) {
        const errorText = await response.text();
        console.error('❌ PaymentMethodService - Error response:', errorText);
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      console.log('✅ PaymentMethodService - Raw response data:', JSON.stringify(data, null, 2));
      console.log('🔍 PaymentMethodService - Data structure check:');
      console.log('  - data.success:', data.success);
      console.log('  - data.data:', data.data);
      console.log('  - data.data?.hasRealPaymentMethods:', data.data?.hasRealPaymentMethods);
      console.log('  - data.data?.paymentMethods?.length:', data.data?.paymentMethods?.length);
      console.log('  - data.hasRealPaymentMethods (direct):', data.hasRealPaymentMethods);
      console.log('  - data.paymentMethods (direct):', data.paymentMethods);
      
      // Extract data from nested structure if it exists
      const responseData = data.data || data;
      const hasRealPaymentMethods = responseData.hasRealPaymentMethods || false;
      const paymentMethods = responseData.paymentMethods || [];
      
      console.log('🎯 PaymentMethodService - Final extracted values:');
      console.log('  - hasRealPaymentMethods:', hasRealPaymentMethods);
      console.log('  - paymentMethods.length:', paymentMethods.length);
      
      return {
        success: true,
        message: 'Payment methods loaded successfully',
        hasRealPaymentMethods,
        paymentMethods,
      };
    } catch (error) {
      console.error('❌ PaymentMethodService Error:', error);
      return {
        success: false,
        message: 'Failed to load payment methods',
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        hasRealPaymentMethods: false,
      };
    }
  }

  static async addPaymentMethod(
    userId: string,
    paymentMethodId: string
  ): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/user/${userId}/add-payment-method`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            paymentMethodId,
          }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment method added successfully',
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Add Payment Method Error:', error);
      return {
        success: false,
        message: 'Failed to add payment method',
        error: error instanceof Error ? error.message : 'Failed to add payment method',
      };
    }
  }

  static async removePaymentMethod(
    userId: string,
    paymentMethodId: string
  ): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/user/${userId}/remove-payment-method`,
        {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            paymentMethodId,
          }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment method removed successfully',
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Remove Payment Method Error:', error);
      return {
        success: false,
        message: 'Failed to remove payment method',
        error: error instanceof Error ? error.message : 'Failed to remove payment method',
      };
    }
  }

  static async getUserStripeCustomerId(
    userId: string,
    userEmail?: string
  ): Promise<{ success: boolean; customerId?: string | null; error?: string }> {
    try {
      if (!this.baseUrl) {
        throw new Error('EXPO_PUBLIC_API_URL environment variable is not set');
      }

      const apiUrl = `${this.baseUrl}/api/stripe/user/${userId}/customer-id`;
      console.log('🔄 PaymentMethodService - Getting customer ID from:', apiUrl);
      console.log('🔄 PaymentMethodService - Base URL:', this.baseUrl);
      
      const response = await fetch(apiUrl, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      console.log('📊 PaymentMethodService - Customer ID response status:', response.status);
      console.log('📊 PaymentMethodService - Customer ID response ok:', response.ok);

      if (!response.ok) {
        const errorText = await response.text();
        console.error('❌ PaymentMethodService - Customer ID error response:', errorText);
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      console.log('✅ PaymentMethodService - Customer ID response data:', data);
      
      if (data.success) {
        return {
          success: true,
          customerId: data.customerId || null,
        };
      } else {
        throw new Error(data.error || 'Failed to get customer ID');
      }
    } catch (error) {
      console.error('❌ Get Customer ID Error:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        customerId: null,
      };
    }
  }

  static async getPaymentMethods(customerId: string): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/customer/${customerId}/payment-methods`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment methods retrieved successfully',
        hasRealPaymentMethods: data.hasRealPaymentMethods || false,
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Get Payment Methods Error:', error);
      return {
        success: false,
        message: 'Failed to get payment methods',
        error: error instanceof Error ? error.message : 'Failed to get payment methods',
        hasRealPaymentMethods: false,
      };
    }
  }

  static async setDefaultPaymentMethod(
    customerId: string,
    paymentMethodId: string
  ): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/customer/${customerId}/default-payment-method`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            paymentMethodId,
          }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Default payment method set successfully',
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Set Default Payment Method Error:', error);
      return {
        success: false,
        message: 'Failed to set default payment method',
        error: error instanceof Error ? error.message : 'Failed to set default payment method',
      };
    }
  }

  static async deletePaymentMethod(paymentMethodId: string): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/payment-method/${paymentMethodId}`,
        {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment method deleted successfully',
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Delete Payment Method Error:', error);
      return {
        success: false,
        message: 'Failed to delete payment method',
        error: error instanceof Error ? error.message : 'Failed to delete payment method',
      };
    }
  }

  // Get detailed payment method information
  static async getPaymentMethodDetails(paymentMethodId: string): Promise<{
    success: boolean;
    paymentMethod?: {
      id: string;
      type: string;
      card?: {
        brand: string;
        last4: string;
        exp_month: number;
        exp_year: number;
        funding: string;
        country: string;
      };
      billing_details?: {
        address?: {
          city?: string;
          country?: string;
          line1?: string;
          line2?: string;
          postal_code?: string;
          state?: string;
        };
        email?: string;
        name?: string;
        phone?: string;
      };
      created: number;
      metadata?: Record<string, string>;
    };
    error?: string;
  }> {
    try {
      if (!this.baseUrl) {
        throw new Error('EXPO_PUBLIC_API_URL environment variable is not set');
      }

      const response = await fetch(
        `${this.baseUrl}/api/stripe/payment-method/${paymentMethodId}/details`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        paymentMethod: data.paymentMethod,
      };
    } catch (error) {
      console.error('Get Payment Method Details Error:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to get payment method details',
      };
    }
  }

  // Update payment method billing details
  static async updatePaymentMethodBillingDetails(
    paymentMethodId: string,
    billingDetails: {
      name?: string;
      email?: string;
      phone?: string;
      address?: {
        city?: string;
        country?: string;
        line1?: string;
        line2?: string;
        postal_code?: string;
        state?: string;
      };
    }
  ): Promise<PaymentMethodResult> {
    try {
      if (!this.baseUrl) {
        throw new Error('EXPO_PUBLIC_API_URL environment variable is not set');
      }

      const response = await fetch(
        `${this.baseUrl}/api/stripe/payment-method/${paymentMethodId}/update`,
        {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ billingDetails }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment method updated successfully',
        paymentMethods: data.paymentMethod ? [data.paymentMethod] : [],
      };
    } catch (error) {
      console.error('Update Payment Method Error:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to update payment method',
        message: 'Failed to update payment method',
      };
    }
  }

  static async createPaymentMethod({
    customerId,
    cardNumber,
    expMonth,
    expYear,
    cvc,
    isUserAdded = true,
    userId,
    email,
    name
  }: {
    customerId?: string;
    cardNumber: string;
    expMonth: number;
    expYear: number;
    cvc: string;
    isUserAdded?: boolean;
    userId?: string;
    email?: string;
    name?: string;
  }): Promise<{ success: boolean; paymentMethod?: PaymentMethod; error?: string; customerId?: string }> {
    console.log('🔍 Creating payment method with params:', {
      customerId,
      cardNumber: cardNumber ? `****${cardNumber.slice(-4)}` : 'none',
      expMonth,
      expYear,
      cvc: '***',
      isUserAdded,
      userId,
      email
    });

    try {
      const response = await fetch(`${this.baseUrl}/api/stripe/create-payment-method`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          customerId,
          cardNumber,
          expMonth,
          expYear,
          cvc,
          isUserAdded,
          userId,
          email,
          name
        }),
      });

      const data = await response.json();
      console.log('✅ Create payment method response:', data);

      if (data.success) {
        return {
          success: true,
          paymentMethod: data.paymentMethod,
          customerId: data.customerId
        };
      } else {
        return {
          success: false,
          error: data.error || data.message || 'Failed to create payment method'
        };
      }
    } catch (error: any) {
      console.error('❌ Error creating payment method:', error);
      return {
        success: false,
        error: error.message || 'Network error while creating payment method'
      };
    }
  }
}

// Initialize and log the service configuration
(function initializePaymentMethodService() {
  console.log('🏗️ PaymentMethodService - Initialized with baseUrl:', process.env.EXPO_PUBLIC_API_URL);
  if (!process.env.EXPO_PUBLIC_API_URL) {
    console.error('❌ PaymentMethodService - EXPO_PUBLIC_API_URL is not set!');
  }
})();
