export interface PaymentMethodResult {
  message?: string;
  success: boolean;
  hasRealPaymentMethods?: boolean;
  paymentMethods?: any[];
  error?: string;
}

export interface PaymentMethod {
  id: string;
  type: string;
  card?: {
    brand: string;
    last4: string;
    exp_month: number;
    exp_year: number;
    funding?: string;
    country?: string;
  };
  created: number;
  isAutoGenerated?: boolean;
  isUserAdded?: boolean;
  isDefault?: boolean;
}

export class PaymentMethodService {
  private static baseUrl = process.env.EXPO_PUBLIC_API_URL;

  static async getPaymentMethodsForUser(
    userId: string,
    userEmail?: string
  ): Promise<PaymentMethodResult> {
    try {
      if (!this.baseUrl) {
        throw new Error('EXPO_PUBLIC_API_URL environment variable is not set');
      }

      const apiUrl = `${this.baseUrl}/api/stripe/user/${userId}/payment-methods`;
      
      const response = await fetch(apiUrl, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        const errorText = await response.text();
        
        let errorData;
        try {
          errorData = JSON.parse(errorText);
        } catch {
          errorData = { error: errorText };
        }

        // Handle "no customer" case gracefully - user hasn't set up Stripe yet
        if (errorData.error?.includes('No Stripe customer found for user')) {
          return {
            success: true,
            message: 'No payment methods set up yet',
            hasRealPaymentMethods: false,
            paymentMethods: []
          };
        }

        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      const hasPaymentMethods = data.hasPaymentMethods || false;
      const paymentMethods = data.paymentMethods || [];
      
      return {
        success: true,
        message: 'Payment methods loaded successfully',
        hasRealPaymentMethods: hasPaymentMethods,
        paymentMethods,
      };
    } catch (error) {
      return {
        success: false,
        message: 'Failed to load payment methods',
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        hasRealPaymentMethods: false,
      };
    }
  }

  static async addPaymentMethod(
    userId: string,
    paymentMethodId: string
  ): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/user/${userId}/add-payment-method`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            paymentMethodId,
          }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment method added successfully',
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Add Payment Method Error:', error);
      return {
        success: false,
        message: 'Failed to add payment method',
        error: error instanceof Error ? error.message : 'Failed to add payment method',
      };
    }
  }

  static async removePaymentMethod(
    userId: string,
    paymentMethodId: string
  ): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/user/${userId}/remove-payment-method`,
        {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            paymentMethodId,
          }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment method removed successfully',
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Remove Payment Method Error:', error);
      return {
        success: false,
        message: 'Failed to remove payment method',
        error: error instanceof Error ? error.message : 'Failed to remove payment method',
      };
    }
  }

  static async getUserStripeCustomerId(
    userId: string,
    userEmail?: string
  ): Promise<{ success: boolean; customerId?: string | null; error?: string }> {
    try {
      if (!this.baseUrl) {
        throw new Error('EXPO_PUBLIC_API_URL environment variable is not set');
      }

      const apiUrl = `${this.baseUrl}/api/stripe/user/${userId}/customer-id`;
      
      const response = await fetch(apiUrl, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });


      if (!response.ok) {
        const errorText = await response.text();
        
        // Parse error to check if it's a "no customer" error
        let errorData;
        try {
          errorData = JSON.parse(errorText);
        } catch {
          errorData = { error: errorText };
        }

        // Handle "no customer" case gracefully - user hasn't set up Stripe yet
        if (response.status === 500 && errorData.error?.includes('No such customer')) {
          console.log('ℹ️ PaymentMethodService - User has no Stripe customer yet (normal for new users)');
          return {
            success: true,
            customerId: null,
          };
        }

        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      if (data.success) {
        return {
          success: true,
          customerId: data.customerId || null,
        };
      } else {
        throw new Error(data.error || 'Failed to get customer ID');
      }
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        customerId: null,
      };
    }
  }

  static async getPaymentMethods(customerId: string): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/customer/${customerId}/payment-methods`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment methods retrieved successfully',
        hasRealPaymentMethods: data.hasRealPaymentMethods || false,
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Get Payment Methods Error:', error);
      return {
        success: false,
        message: 'Failed to get payment methods',
        error: error instanceof Error ? error.message : 'Failed to get payment methods',
        hasRealPaymentMethods: false,
      };
    }
  }

  static async setDefaultPaymentMethod(
    userId: string,
    paymentMethodId: string
  ): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/user/${userId}/default-payment-method`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            paymentMethodId,
          }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Default payment method set successfully',
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Set Default Payment Method Error:', error);
      return {
        success: false,
        message: 'Failed to set default payment method',
        error: error instanceof Error ? error.message : 'Failed to set default payment method',
      };
    }
  }

  static async deletePaymentMethod(paymentMethodId: string): Promise<PaymentMethodResult> {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/stripe/payment-method/${paymentMethodId}`,
        {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment method deleted successfully',
        paymentMethods: data.paymentMethods || [],
      };
    } catch (error) {
      console.error('Delete Payment Method Error:', error);
      return {
        success: false,
        message: 'Failed to delete payment method',
        error: error instanceof Error ? error.message : 'Failed to delete payment method',
      };
    }
  }

  // Get detailed payment method information
  static async getPaymentMethodDetails(paymentMethodId: string): Promise<{
    success: boolean;
    paymentMethod?: {
      id: string;
      type: string;
      card?: {
        brand: string;
        last4: string;
        exp_month: number;
        exp_year: number;
        funding: string;
        country: string;
      };
      billing_details?: {
        address?: {
          city?: string;
          country?: string;
          line1?: string;
          line2?: string;
          postal_code?: string;
          state?: string;
        };
        email?: string;
        name?: string;
        phone?: string;
      };
      created: number;
      metadata?: Record<string, string>;
    };
    error?: string;
  }> {
    try {
      if (!this.baseUrl) {
        throw new Error('EXPO_PUBLIC_API_URL environment variable is not set');
      }

      const response = await fetch(
        `${this.baseUrl}/api/stripe/payment-method/${paymentMethodId}/details`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        paymentMethod: data.paymentMethod,
      };
    } catch (error) {
      console.error('Get Payment Method Details Error:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to get payment method details',
      };
    }
  }

  // Update payment method billing details
  static async updatePaymentMethodBillingDetails(
    paymentMethodId: string,
    billingDetails: {
      name?: string;
      email?: string;
      phone?: string;
      address?: {
        city?: string;
        country?: string;
        line1?: string;
        line2?: string;
        postal_code?: string;
        state?: string;
      };
    }
  ): Promise<PaymentMethodResult> {
    try {
      if (!this.baseUrl) {
        throw new Error('EXPO_PUBLIC_API_URL environment variable is not set');
      }

      const response = await fetch(
        `${this.baseUrl}/api/stripe/payment-method/${paymentMethodId}/update`,
        {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ billingDetails }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      return {
        success: true,
        message: 'Payment method updated successfully',
        paymentMethods: data.paymentMethod ? [data.paymentMethod] : [],
      };
    } catch (error) {
      console.error('Update Payment Method Error:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to update payment method',
        message: 'Failed to update payment method',
      };
    }
  }

  static async createPaymentMethod({
    customerId,
    cardNumber,
    expMonth,
    expYear,
    cvc,
    isUserAdded = true,
    userId,
    email,
    name
  }: {
    customerId?: string;
    cardNumber: string;
    expMonth: number;
    expYear: number;
    cvc: string;
    isUserAdded?: boolean;
    userId?: string;
    email?: string;
    name?: string;
  }): Promise<{ success: boolean; paymentMethod?: PaymentMethod; error?: string; customerId?: string }> {

    try {
      const response = await fetch(`${this.baseUrl}/api/stripe/create-payment-method`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          customerId,
          cardNumber,
          expMonth,
          expYear,
          cvc,
          isUserAdded,
          userId,
          email,
          name
        }),
      });

      const data = await response.json();

      if (data.success) {
        return {
          success: true,
          paymentMethod: data.paymentMethod,
          customerId: data.customerId
        };
      } else {
        return {
          success: false,
          error: data.error || data.message || 'Failed to create payment method'
        };
      }
    } catch (error: any) {
      console.error('❌ Error creating payment method:', error);
      return {
        success: false,
        error: error.message || 'Network error while creating payment method'
      };
    }
  }
}

// Initialize and log the service configuration
(function initializePaymentMethodService() {
  if (!process.env.EXPO_PUBLIC_API_URL) {
    console.error('❌ PaymentMethodService - EXPO_PUBLIC_API_URL is not set!');
  }
})();
